name: Ubuntu 22.04 VM image build
run-name: Ubuntu 22.04 VM image build
on:
  workflow_dispatch:

#  schedule:
#    - cron: '0 9 * * 4' # Every Thursday at 9am UTC to avoid alerts during weekend for regular build activities.

env:
  RUNNER_IMAGES_VERSION: 'main'                               # actions/runner-images version to use
  PACKER_TEMPLATE: './images/ubuntu-22.04.pkr.hcl'
  PACKER_VERSION: '1.8.7'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_RESOURCE_LOCATION: 'west europe'
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  MANAGED_IMAGE_NAME: 'ubuntu_2204_v2'
  MANAGED_IMAGE_RESOURCE_GROUP_NAME: 'rg-match-ai'


permissions:
  id-token: write
  contents: read
  repository-projects: read

jobs:
  packer:
    runs-on: az-u2404-vdm
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout actions/runner-images repo version
        uses: actions/checkout@v4
        with:
          repository: actions/runner-images
          ref: ${{ env.RUNNER_IMAGES_VERSION }}
          path: runner-images

      # Copy our Packer templates and custom installers into runner-images hive
      - name: Copy custom files to runner-images
        run: |
          mv ./runner-images/images/ubuntu/templates/ubuntu-22.04.pkr.hcl ./runner-images/images/ubuntu/templates/ubuntu-22.04.pkr.hcl.original
          cp ./images/ubuntu-22.04.pkr.hcl ./runner-images/images/ubuntu/templates/ubuntu-22.04.pkr.hcl
          cp -R ./images/custom/installers/* ./runner-images/images/ubuntu/scripts/build/

      # Get an image end-of-life date - 2 months in future
      - name: Get image end-of-life date
        id: end-of-life-date
        shell: bash -o errexit -o xtrace {0}
        env:
          DATE: 2 months
          FORMAT: '%Y-%m-%dT%H:%M:%S.00Z'
        run: |
          echo "date=$(date --date="$DATE" --utc +"$FORMAT")" >> "$GITHUB_OUTPUT"

      # download desired version of Packer
      - name: Download desired Packer version
        uses: hashicorp/setup-packer@v3
        with:
          version: ${{ env.PACKER_VERSION }}

      # validate template
      - name: Validate Template
        run: packer validate -syntax-only ${{ env.PACKER_TEMPLATE }}

      # build new image if this is a manual run, scheduled, or a push to main
      - name: Build New Image
        id: BuildNewImage
        run: |
          packer init ${{ env.PACKER_TEMPLATE }}
          packer build -color=false -force -on-error=cleanup ${{ env.PACKER_TEMPLATE }}
        env:
          PACKER_LOG: 1
          SHARED_IMAGE_GALLERY_END_OF_LIFE_DATE: "${{ steps.end-of-life-date.outputs.date }}"
